name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: SumUpToTest.PositiveNumbers
      id: sumuptotest-positivenumbers
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SumUpToTest.PositiveNumbers
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 5
    - name: SumUpToTest.EdgeCases
      id: sumuptotest-edgecases
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SumUpToTest.EdgeCases
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUMUPTOTEST-POSITIVENUMBERS_RESULTS: "${{steps.sumuptotest-positivenumbers.outputs.result}}"
        SUMUPTOTEST-EDGECASES_RESULTS: "${{steps.sumuptotest-edgecases.outputs.result}}"
      with:
        runners: sumuptotest-positivenumbers,sumuptotest-edgecases
