name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: SumUpTo.PositiveNumbers
      id: sumupto-positivenumbers
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SumUpTo.PositiveNumbers
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 5
    - name: SumUpTo.EdgeCases
      id: sumupto-edgecases
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SumUpTo.EdgeCases
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUMUPTO-POSITIVENUMBERS_RESULTS: "${{steps.sumupto-positivenumbers.outputs.result}}"
        SUMUPTO-EDGECASES_RESULTS: "${{steps.sumupto-edgecases.outputs.result}}"
      with:
        runners: sumupto-positivenumbers,sumupto-edgecases
